# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'sdk_demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # AdQuanta Ads SDK (包含所有依赖，无需额外添加)
  # pod 'adquanta-ads-sdk', '~> 1.0.1'
  
  # TradPlus 测试工具（可选，用于调试）
  # pod "TPMediationHelper", '1.2.0'
end


